DROP TABLE IF EXISTS CITY;
--CREATE TABLE CITY (
--City_code INT AUTO_INCREMENT  PRIMARY KEY,
--city_name VARCHAR(50) NOT NULL,
--city_pin INT NOT NULL,
--city_namea VARCHAR(50) NOT NULL
--);


CREATE TABLE Trade_Data (
id INTEGER AUTO_INCREMENT  PRIMARY KEY,
First_name VARCHAR(100) NOT NULL,
Last_Name VARCHAR(100) NOT NULL,
Nationality VARCHAR(100) NOT NULL,
Country_of_Residence VARCHAR(100) NOT NULL,
date_of_birth VARCHAR(100) NOT NULL,
Unique_Trader_id VARCHAR(100) NOT NULL,
Amount VARCHAR(100) NOT NULL,
currency VARCHAR(100) NOT NULL,
unique_Stock_ID VARCHAR(100) NOT NULL,
Buy_or_Sell VARCHAR(100) NOT NULL,
trade_time TIMESTAMP,
Fraud_Flag VARCHAR(10)
);